DROP DATABASE IF EXISTS PinPal;
CREATE DATABASE PinPal;
USE PinPal;

CREATE TABLE User (
	id INT UNSIGNED AUTO_INCREMENT,
	username VARCHAR(64) UNIQUE NOT NULL,
	password CHAR(60) NOT NULL,
	displayName VARCHAR(64) UNIQUE NOT NULL,
	CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE TABLE Conversation (
	id INT UNSIGNED AUTO_INCREMENT,
	CONSTRAINT pk_conversation PRIMARY KEY (id)
);

CREATE TABLE ConversationParticipant (
	conversationId INT UNSIGNED NOT NULL,
	userId INT UNSIGNED NOT NULL,
	CONSTRAINT pk_conversationParticipants PRIMARY KEY (conversationId, userId),
	CONSTRAINT fk_conversationParticipants_conversationId FOREIGN KEY (conversationId) REFERENCES Conversation(id) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT fk_conversationParticipants_userId FOREIGN KEY (userId) REFERENCES User(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Message (
	id INT UNSIGNED AUTO_INCREMENT,
	conversationId INT UNSIGNED NOT NULL,
	authorId INT UNSIGNED NOT NULL,
	text TEXT NOT NULL,
	timestamp DATETIME NOT NULL,
	CONSTRAINT pk_message PRIMARY KEY (id),
	CONSTRAINT fk_message_conversationId FOREIGN KEY (conversationId) REFERENCES Conversation(id) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT fk_message_authorId FOREIGN KEY (authorId) REFERENCES User(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Board (
	id INT UNSIGNED AUTO_INCREMENT,
	name VARCHAR(64) NOT NULL,
	ownerId INT UNSIGNED,
	private ENUM('true', 'false') DEFAULT 'false',
	conversationId INT UNSIGNED,
	lockedForEditingById INT UNSIGNED DEFAULT NULL,
	lockedForEditingOn DATETIME DEFAULT NULL,
	CONSTRAINT pk_board PRIMARY KEY (id),
	CONSTRAINT fk_board_ownerId FOREIGN KEY (ownerId) REFERENCES User(id) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT fk_board_conversationId FOREIGN KEY (conversationId) REFERENCES Conversation(id) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT fk_board_lockedForEditingById FOREIGN KEY (lockedForEditingById) REFERENCES User(id) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE BoardEditor (
	userId INT UNSIGNED,
	boardId INT UNSIGNED,
	CONSTRAINT pk_boardEditors PRIMARY KEY (userId, boardId),
	CONSTRAINT fk_boardEditors_userId FOREIGN KEY (userId) REFERENCES User(id) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT fk_boardEditors_boardId FOREIGN KEY (boardId) REFERENCES Board(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Shape (
	id INT UNSIGNED AUTO_INCREMENT,
	boardId INT UNSIGNED,
	strokeWidth INT UNSIGNED NOT NULL DEFAULT 3,
	strokeColor VARCHAR(7) NOT NULL DEFAULT '#34495E',
	fillColor VARCHAR(7) NOT NULL DEFAULT '#9B59B6',
	CONSTRAINT pk_shape PRIMARY KEY (id),
	CONSTRAINT pk_shape_boardId FOREIGN KEY (boardId) REFERENCES Board(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Line (
	shapeId INT UNSIGNED,
	x1 INT UNSIGNED NOT NULL DEFAULT 0,
	y1 INT UNSIGNED NOT NULL DEFAULT 0,
	x2 INT UNSIGNED NOT NULL DEFAULT 5,
	y2 INT UNSIGNED NOT NULL DEFAULT 5,
	CONSTRAINT pk_line PRIMARY KEY (shapeId),
	CONSTRAINT pk_line_shapeId FOREIGN KEY (shapeId) REFERENCES Shape(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Rect (
	shapeId INT UNSIGNED,
	x INT UNSIGNED NOT NULL DEFAULT 0,
	y INT UNSIGNED NOT NULL DEFAULT 0,
	width INT UNSIGNED NOT NULL DEFAULT 5,
	height INT UNSIGNED NOT NULL DEFAULT 5,
	CONSTRAINT pk_rect PRIMARY KEY (shapeId),
	CONSTRAINT pk_text_shapeId FOREIGN KEY (shapeId) REFERENCES Shape(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Circle (
	shapeId INT UNSIGNED,
	r DOUBLE(5,1) UNSIGNED NOT NULL DEFAULT 2.5,
	cx INT UNSIGNED NOT NULL DEFAULT 5,
	cy INT UNSIGNED NOT NULL DEFAULT 5,
	CONSTRAINT pk_circle PRIMARY KEY (shapeId),
	CONSTRAINT pk_circle_shapeId FOREIGN KEY (shapeId) REFERENCES Shape(id) ON UPDATE CASCADE ON DELETE CASCADE
);


INSERT INTO User (id, username, password, displayname)
VALUES (1, 'PinPal', '000000000000000000000000000000000000000000000000000000000000', 'PinPal');

INSERT INTO Conversation (id)
VALUES (1);

INSERT INTO Board (id, name, ownerId, private, conversationId)
VALUES (1, 'Lobby', 1, 'false', 1);
